drop table if exists tempvol;

create table tempvol (
  contact varchar(60),
  firstName varchar(20),
  lastname varchar(20),
  city varchar(30),
  email varchar(50),
  phone varchar(20),
  interests varchar(1000),
  htmlcss integer,
  js integer,
  react integer,
  node integer,
  agile integer,
  other varchar(1000),
  teachwe varchar(1000),
  skills varchar(1000),
  avail varchar(1000),
  status varchar(200),
  submitdt numeric,
  comments varchar(1000),
  welcomedt numeric,
  onboarddt numeric
);

INSERT INTO tempVol (contact, firstName, lastName, city, email, phone, interests, 
                     htmlcss, js, react, node, agile, other, teachwe, skills, avail, 
                     status, submitdt, comments, welcomedt, onboarddt)
  VALUES ('Iwan Hepburn London (UK)', 'Iwan','Hepburn','London (UK)','hi@iwanhepburn.de','07001234567',
            'Teaching code or agile methodologies, Running and growing the organisation', 
            5,5,null,5,4,null,null,'Accounting / Bookkeeping, Coaching, NGO and Corporate Outreach / Fundraising / Partnerships, Project Management / Business Analysis, Volunteer Engagement / Community Management',
            'During our classes on Saturdays/Sundays, During the week',
            'Contacted',null,null,43545.64429,null),
         ('Ilanit Yu Rome (Italy)','Ilanit','Yu','Rome (Italy)','ilanit@yahoo.com','03201234567',
            'Running and growing the organisation',null,null,null,null,null,null,null,
            'Growth Marketing / Social Media Strategy, Personal Support Work / Wellbeing',
            'During our classes on Saturdays/Sundays','Signed Up',43547.75,
            'Email and texts sent -will come to meet up 25/3/19',null,null),
         ('Gretta Wilcox Glasgow (UK)','Gretta','Wilcox','Glasgow (UK)','example@googlemail.com',
            '078881234567',
            'Running and growing the organisation, Teaching code or agile methodologies',
            4,4,null,3,3,'User Interface/User Experience design and implementation. Creating portfolio projects for potential employers.',
            null,'Coaching, Event Management, Volunteer Engagement / Community Management, Graduate Job Placement (Recruitment), Pedagogy / Learning Environments, Personal Support Work / Wellbeing, Photography / Videography, Project Management / Business Analysis',
            'During our classes on Saturdays/Sundays, During the week, Other','Signed Up',
            43548.54167,'Emailed 24/03/19',null,null),
         ('Kayode Choi Medellín (Colombia)','Kayode','Choi','Medellín (Colombia)','choi999@gmail.com','03501234567',
            'Teaching code or agile methodologies, Running and growing the organisation',
            2,2,null,1,1,'Java, Python, AWS, Azure, DevOps culture',null,
            'Growth Marketing / Social Media Strategy, Photography / Videography, Volunteer Engagement / Community Management, Pedagogy / Learning Environments, Coaching, Event Management','During our classes on Saturdays/Sundays, During the week',
            'New',43549.17907,null,null,null),
         ('Nadav Stern London (UK)','Nadav','Stern','London (UK)','nstern68@greenmail.com','07741234567',
            'Running and growing the organisation',null,null,null,null,null,null,null,null,
            'During our classes on Saturdays/Sundays, During the week','New',43550.60332,null,null,null),
         ('Ata Anson London (UK)','Ata','Anson','London (UK)','purplehaze@greenmail.com','07751234567',
            'Teaching code or agile methodologies, Running and growing the organisation',2,1,null,4,4,null,null,
            'Coaching, Graduate Job Placement (Recruitment), Photography / Videography',
            'Other, During our classes on Saturdays/Sundays, During the week','Contacted',
            43551.47601,'24/04/19 email sent – Jonny',null,null),
         ('Tyler Terry London (UK)','Tyler','Terry','London (UK)','tyler@example.com',null,
            'Running and growing the organisation',null,null,null,null,null,null,null,
            'Volunteer Engagement / Community Management, Pedagogy / Learning Environments, Project Management / Business Analysis, NGO and Corporate Outreach / Fundraising / Partnerships, Event Management, Graduate Job Placement (Recruitment), Growth Marketing / Social Media Strategy, Journalism / Writing, Coaching',
            'Other, During the week','Contacted',43551.89315,'29/03/19 email sent – Jonny',null,null),
         ('Ghassan Stroud Manchester (UK)','Ghassan','Stroud','Manchester (UK)','ghazzadhi@greenmail.com',
            null,'Teaching code or agile methodologies, Running and growing the organisation',3,4,null,3,3,null,null,
            'Event Management, Coaching, Journalism / Writing, Volunteer Engagement / Community Management, Pedagogy / Learning Environments',
            'During the week, During our classes on Saturdays/Sundays','Contacted',43552.88213,
            'emailed 31/03 - phone number requested for initial discussion. chris@manchester',null,null),
         ('Somhairle Derricks Rome (Italy)','Somhairle','Derricks','Rome (Italy)',
            'somhairle_1996@liveit.com','03341234567','Running and growing the organisation',
            null,null,null,null,null,null,null,
            'Project Management / Business Analysis','During our classes on Saturdays/Sundays','Contacted',
            43553.31479,'emailed 29/03. Met at drop in session 1/4/19',null,null),
         ('Mansoor Hunnicutt Rome (Italy)','Mansoor','Hunnicutt','Rome (Italy)',
            'marveloso693@greenmail.com','03291234567','Running and growing the organisation',
            null,null,null,null,null,null,null,null,'During our classes on Saturdays/Sundays, Other',
            'Contacted',43553.33013,'emailed 29/03. Will come to interview day 13/04',null,null),
         ('Art Kendrick London (UK)','Art','Kendrick','London (UK)','aarrtt@greenmail.com','07843210987',
            'Running and growing the organisation',null,null,null,null,null,null,null,
            'Journalism / Writing, Personal Support Work / Wellbeing, Growth Marketing / Social Media Strategy, Volunteer Engagement / Community Management',
            'During our classes on Saturdays/Sundays','New',43553.54414,null,null,null),
         ('Kaitlin McKendrick Rome (Italy)','Kaitlin','McKendrick','Rome (Italy)','kait.mck@greenmail.com','03911234567',
            'Teaching code or agile methodologies, Running and growing the organisation',2,2,null,2,2,
            'Java, php, networking',null,
            'Coaching, Growth Marketing / Social Media Strategy, Project Management / Business Analysis, Photography / Videography','During our classes on Saturdays/Sundays, During the week'
            ,'Contacted',43554.23506,'emailed 2/4/19, messaged 4/4/19. Met and signed up 11/04',null,null),
         ('Maci Afolabi Rome (Italy)','Maci','Afolabi','Rome (Italy)','maci.afolabi@greenmail.com',null,
            'Running and growing the organisation, Teaching code or agile methodologies',2,1,null,2,1,
            'I am familiar with many CMS and a bit with databases',null,
            'Accounting / Bookkeeping, Journalism / Writing, Pedagogy / Learning Environments, Photography / Videography, Personal Support Work / Wellbeing, Volunteer Engagement / Community Management',
            'During our classes on Saturdays/Sundays, During the week','Contacted',43555.03598,'emailed 2/4/19',null,null),
         ('Fawzi Stirling Rome (Italy)','Fawzi','Stirling','Rome (Italy)','fawzi.beer@greenmail.com','03331234567',
            'Running and growing the organisation',null,null,null,null,null,null,null,
            'Project Management / Business Analysis','During our classes on Saturdays/Sundays',
            'Contacted',43555.08494,'emailed 2/4/19',null,null),
         ('Cayley Newport London (UK)','Cayley','Newport','London (UK)','cayley.newport494@greenmail.com','07901234567',
            'Teaching code or agile methodologies, Running and growing the organisation',4,4,null,4,4,
            'Ruby/Rails, a bit of Java',null,
            'Coaching, Journalism / Writing, Pedagogy / Learning Environments',
            'During our classes on Saturdays/Sundays, During the week','Contacted',43557.59705,
            '29/04/19 email sent – Jonny',null,null),
         ('Homer Simpson Rome (Italy)','Homer','Simpson','Rome (Italy)','homer.simpson@notmail.it',
            null,'Running and growing the organisation',null,null,null,null,null,null,null,
            'Event Management, Graduate Job Placement (Recruitment), Coaching, Growth Marketing / Social Media Strategy',
            'During our classes on Saturdays/Sundays','New',43559.6886,
            'friend of friend of Germán. Will have an initial chat with him (G)',null,null),
         ('Dian Li Glasgow (UK)','Dian','Li','Glasgow (UK)','dian@lidiandesigns.com','07941234567',
            'Running and growing the organisation, Teaching code or agile methodologies',5,4,3,3,4,
            'BSc Hons 2:1 degree, 5+ years commercial experience, 10+ years overall experience.',null,
            'Coaching, Event Management, Graduate Job Placement (Recruitment), Growth Marketing / Social Media Strategy, Journalism / Writing, Personal Support Work / Wellbeing, Project Management / Business Analysis, Volunteer Engagement / Community Management',
            'During our classes on Saturdays/Sundays, During the week, Other','New',43581.41787,null,null,null),
         ('Georgeanna Broadbent Glasgow (UK)','Georgeanna','Broadbent','Glasgow (UK)','georgeanna.broadbent@greenmail.com',
            '07591234567','Running and growing the organisation',null,null,null,null,null,null,null,
            'Event Management, Accounting / Bookkeeping, Photography / Videography, Project Management / Business Analysis, Volunteer Engagement / Community Management, Pedagogy / Learning Environments, Growth Marketing / Social Media Strategy, NGO and Corporate Outreach / Fundraising / Partnerships',
            'During our classes on Saturdays/Sundays, During the week','New',43600.76932,null,null,null),
         ('Sari Cole Medellín (Colombia)','Sari','Cole','Medellín (Colombia)','saricole@outlook.com',
            '03021234567','Teaching code or agile methodologies, Running and growing the organisation',
            4,4,3,4,3,null,null,
            'Coaching, Graduate Job Placement (Recruitment), Journalism / Writing, Pedagogy / Learning Environments, Project Management / Business Analysis, Volunteer Engagement / Community Management, Event Management, Personal Support Work / Wellbeing',
            'During our classes on Saturdays/Sundays, Other, During the week','New',43612.92704,null,null,null),
         ('Taisia Irving Manchester (UK)','Taisia','Irving','Manchester (UK)','taisia@greenmail.com',
            '07761234567','Teaching code or agile methodologies, Running and growing the organisation',
            1,1,1,1,1,null,null,
            'Growth Marketing / Social Media Strategy, Graduate Job Placement (Recruitment), Event Management, Coaching, Accounting / Bookkeeping, Journalism / Writing, Photography / Videography, Volunteer Engagement / Community Management',
            'During the week','New',43620.80146,null,null,null),
         ('fdd dfd Manchester (UK)','fdd','dfd','Manchester (UK)','dfd@gmailc.om','07461234567',
            'Teaching code or agile methodologies, Running and growing the organisation',5,5,5,5,5,
            'jhjh',null,'Accounting / Bookkeeping, Coaching, Event Management',
            'During our classes on Saturdays/Sundays, Other, During the week','New',43621.83615,null,null,null),
         ('Shannon Saitou Glasgow (UK)','Shannon','Saitou','Glasgow (UK)','saitou87@greenmail.com',
           '07441234567','Running and growing the organisation, Teaching code or agile methodologies',
            4,4,null,null,null,'php wordpress css',null,
            'Personal Support Work / Wellbeing, Project Management / Business Analysis, Volunteer Engagement / Community Management, Event Management, Growth Marketing / Social Media Strategy',
            'During the week','New',43622.59372,null,null,null);

